### ISSUE TITLE
Vysor FEATURE REQUEST: On the screenshot popup, allow the shortcut of a key (such as enter) to go into the SAVE prompt

### ISSUE THREAD

**Issue by npfister13** [koush/vysor.io#796] opened 2021-06-07 13:07 UTC
Minor request. Being able to hit ENTER when on the popup prompt to go into the SAVE prompt would be beneficial for decreasing time it takes to save a screenshot. This would be especially handy for those, such as myself, that has to take dozens if not hundreds of screenshots on devices.

Thank you.

**Comment by koush** [comment] 2021-06-07 16:51
This is a duplicate of another issue and has already been fixed! It will be in the beta channel shortly. You’ll be able to set the default behavior in device settings.

**Closed by koush** 2021-06-07 16:51 UTC
