### ISSUE TITLE
PC touchscreen taps not sent to device

### ISSUE THREAD

**Issue by kirk7morris** [koush/vysor.io#484] opened 2020-05-02 00:31 UTC
Just upgraded - looks excellent. Mouse clicks / swipes work fine BUT I have a touchscreen laptop - touches are not doing anything. Tried it on a second laptop - same issue. Previous version (2.3.0) worked fine on both. 

Windows 10 2020. Vysor 3.0.57

https://gist.github.com/9efc91d6dfbc2b43679f3cb107a919e7

**Comment by koush** [comment] 2020-05-02 01:47
Thanks, will fix this.

**Comment by kirk7morris** [comment] 2020-05-02 03:11
koush you are awesome, love your work.

**Comment by mattenuttall** [comment] 2020-05-02 15:05
Hi Guys; I'm glad this has been reported. I just upgraded to the paid version of Vysor hoping to get my touchscreen taps working again after the upgrade. No luck. I use Vysor constantly. Do you know when this will be fixed? How will I know when I can upgrade to the fixed version of Vysor? Sorry for the dumb questions. Great product!

**Comment by koush** [comment] 2020-05-03 03:40
Tonight or tomorrow

**Comment by mattenuttall** [comment] 2020-05-05 15:42
Hi Koush;
I just loaded the latest version, 3.0.62, but unfortunately finger taps on my touchscreen Surface Pro 2 running Windows 10 still don't work. The mouse still works fine. Let me know if I can help with diagnostics or anything.
Thanks!  Matt

**Comment by koush** [comment] 2020-05-05 20:05
Just fixed this in 3.0.64. I do not have a touch screen device, but was able to emulate touches with Chrome inspector. Please verify.

**Comment by kirk7morris** [comment] 2020-05-05 22:03
@koush Working perfectly well for me (now on 3.0.65) - thank you so much. What's the best way for me to support your work?

**Comment by koush** [comment] 2020-05-05 22:12
@kirk7morris purchase a sub if you haven't! thanks!

**Comment by mattenuttall** [comment] 2020-05-06 02:00
Your amazing, Koushik. Thank you, it works perfectly...

________________________________

**Comment by mattenuttall** [comment] 2020-05-06 17:06
Hmm, as of version 3.0.67, screen taps are not working. Although, they seem to occasionally work. I'm back to using mouse again. Do you guys have a "real" WIndows 10 touch screen (perhaps a Surface Pro) you can test on? Thanks again -- Matt

**Comment by mattenuttall** [comment] 2020-05-06 17:08
Ah, I figured it out: the when I tap at location "x,y" on the screen, the tap doesn't is processed about 1cm lower than were I tapped. Makes for some messy confusing exchanges. Basically, the tap location is not calibrated to the correct device screen position. This all used to work perfectly before the latest round of upgrades, by the way. Thanks again.

**Comment by koush** [comment] 2020-05-06 18:40
@mattenuttall I think I have an idea of what the issue is.

**Comment by koush** [comment] 2020-05-06 18:53
Can you verify the fix in 3.0.70?

**Comment by mattenuttall** [comment] 2020-05-06 18:55
Waa aaa aaaaa! That is so much better. Touch screen seems to be very accurate now. Thank you again, Koush. You're amazing. Give yourself a raise, a pat on the back, tell your manager you're great....

All the best - Matt

________________________________

**Closed** 2020-05-06 19:00 UTC
