### ISSUE TITLE
Always black screen

### ISSUE THREAD

**Issue by m4xp1** [koush/vysor.io#422] opened 2019-12-16 08:25 UTC
More than a year has passed since I tried your product, but to my regret, it still does not work. I changed my computer, installed a new version of the operating system, but I get a black screen ((( How can I get your product to work on KUbuntu 19.10? I read the help about the error but there is only a description for Windows that doesn’t work for me. I tried to unload the built-in module video cards, but it didn’t help, or it didn’t work out. Here's what `lspci -v | grep VGA `shows:

```
08:01.0 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200eW WPCM450 (rev 0a) (prog-if 00 [VGA controller]) DeviceName: Onboard Matrox VGA 
83:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E] (prog-if 00 [VGA controller])
```

Tell me how to fix the problem?

[Screen with error](https://i.ibb.co/vYTNRgR/Screenshot-20191216-110754.png)

**Comment by koush** [comment] 2020-01-19 20:13
you on multiple monitors or a VM? Can you try with 1 monitor, or your primary monitor?

**Comment by m4xp1** [comment] 2020-01-25 17:25
Yes, I use a system with multiple monitors. I tried running Vysor 2.2.1 with one monitor and got the same error. I also tried to run the application only on the integrated video card without a discrete one and got the same error. The application unfortunately does not work.

**Comment by TitusLabienus** [comment] 2020-02-13 10:04
@koush @m4xp1
On Arch Linux I also had the black screen issue, but only with the package 'vysor-git'. Since then, somebody has thankfully created the package 'vysor-appimage', which works fine. Maybe the Ubunu package is also missing what the difference (whatever that may be) between the 'vysor-git' and the 'vysor-appimage'. (Maybe some missing dependency?) So figuring out the difference might give away what the problem is here too.

**Comment by koush** [comment] 2020-02-14 19:04
I have a fix for this coming that relies on a new rendering engine that will likely fix this.

Can you confirm this works? https://get.webgl.org/

**Comment by koush** [comment] 2020-04-15 06:00
https://github.com/koush/vysor.io/issues

**Closed by koush** 2020-04-15 06:00 UTC
Labels: duplicate
