### ISSUE TITLE
Vysor update broke software?

### ISSUE THREAD

**Issue by willownikki** [koush/vysor.io#837] opened 2021-07-12 02:12 UTC
Vysor worked last week, launched Vysor this afternoon and it stalled, had to force close it due to it being unresponsive. Relaunched it and got this:
![Screenshot 2021-07-11 190044](https://user-images.githubusercontent.com/54648126/125219793-554e1480-e27a-11eb-80dc-40ed1824bb3c.png)
 
I have fully uninstalled this using revo uninstaller, restarted my pc and did a fresh install from the website. Still no change. 
![Screenshot 2021-07-11 191305](https://user-images.githubusercontent.com/54648126/125220751-0acd9780-e27c-11eb-8b67-68b13ffcaca5.png)

2021-07-11 19:09:12> Program: Starting Squirrel Updater: --createShortcut=Vysor.exe
2021-07-11 19:09:12> ApplyReleasesImpl: About to create shortcuts for Vysor.exe, rootAppDir C:\Users\pan_n\AppData\Local\vysor
2021-07-11 19:09:12> ApplyReleasesImpl: Creating shortcut for Vysor.exe => C:\Users\pan_n\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Vysor Inc.\Vysor.lnk
2021-07-11 19:09:12> ApplyReleasesImpl: About to save shortcut: C:\Users\pan_n\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Vysor Inc.\Vysor.lnk (target C:\Users\pan_n\AppData\Local\vysor\Vysor.exe, workingDir C:\Users\pan_n\AppData\Local\vysor\app-4.1.29, args , toastActivatorCSLID e43a84ce-403c-55db-b5f1-e5e886dcd138)
2021-07-11 19:09:13> ApplyReleasesImpl: Creating shortcut for Vysor.exe => C:\Users\pan_n\OneDrive\Desktop\Vysor.lnk
2021-07-11 19:09:13> ApplyReleasesImpl: About to save shortcut: C:\Users\pan_n\OneDrive\Desktop\Vysor.lnk (target C:\Users\pan_n\AppData\Local\vysor\Vysor.exe, workingDir C:\Users\pan_n\AppData\Local\vysor\app-4.1.29, args , toastActivatorCSLID e43a84ce-403c-55db-b5f1-e5e886dcd138)
2021-07-11 19:09:13> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2021-07-11 19:09:13> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2021-07-11 19:09:13> ApplyReleasesImpl: Examining Pin: Opera GX Browser.lnk
2021-07-11 19:09:13> Program: Starting Squirrel Updater: --checkForUpdate https://nuts.vysor.io/update/win32_x64/4.1.29
2021-07-11 19:09:13> Program: Fetching update information, downloading from https://nuts.vysor.io/update/win32_x64/4.1.29
2021-07-11 19:09:14> CheckForUpdateImpl: Generated new staging user ID: 5d4ad102-dfe9-5dce-967f-e0cfcfecc660
2021-07-11 19:09:14> CheckForUpdateImpl: Downloading RELEASES file from https://nuts.vysor.io/update/win32_x64/4.1.29
2021-07-11 19:09:14> FileDownloader: Downloading url: https://nuts.vysor.io/update/win32_x64/4.1.29/RELEASES?id=vysor&localVersion=4.1.29&arch=amd64

Let me know if I need to provide anything else.

**Comment by koush** [comment] 2021-07-12 04:49
Try deleting:

C:\Users\YOUR_USER_NAME\Local\vysor
C:\Users\YOUR_USER_NAME\Roaming\vysor

and uninstalling, then reinstalling.

**Comment by koush** [comment] 2021-07-12 04:52
You can also try launching that Vysor.ee from the command line and you may see more errors in the resulting terminal.

**Comment by koush** [comment] 2021-07-12 04:53
Finally, may just want to try restarting in case some process is stuck. Let me know any of these work.

**Comment by boynet** [comment] 2021-07-12 13:48
same error here, deleting the folders and reinstall does not help

**Comment by koush** [comment] 2021-07-12 17:55
This seems to be an issue with some antivirus site erroneously marking it as "malicious" preventing the app from receiving updates and loading.

You can get the prerelease which works around this (select the beta channel once launched):

https://github.com/koush/vysor.io/releases/tag/v4.1.45

**Comment by koush** [comment] 2021-07-13 23:40
https://github.com/koush/vysor.io/releases/tag/v4.1.47

**Comment by koush** [comment] 2021-07-15 08:00
Confirmed fixed as this is off the dr web false positive list

**Closed by koush** 2021-07-15 08:00 UTC
