### ISSUE TITLE
HTC M8 not working

### ISSUE THREAD

**Issue by vevinmoza** [koush/vysor.io#14] opened 2015-08-25 15:03 UTC
Installed the universal adb driver on windows but it still can't connect to my HTC M8.

**Comment by karnatisandeep** [comment] 2015-08-25 16:23
![vysor](https://cloud.githubusercontent.com/assets/9047437/9472538/abc8bcba-4b73-11e5-8f33-83fb7cf7f946.PNG)

My HTC One E8 device is showing like this.. and selecting it causes nothing..

**Comment by vevinmoza** [comment] 2015-08-26 17:24
Ya i have the same issue.. it doesn't do anything after that.. it shows a blank screen after "select"

**Comment by LootenPlunder** [comment] 2015-08-26 20:53
What version of windows? Apparently the universal won't work with 10.

**Comment by koush** [comment] 2015-08-26 21:11
Correct, universal won't work. I'm trying to figure out a fix, i know what the issue is. In the meantime, use the manufacturer driver.

**Comment by koush** [comment] 2015-08-27 02:30
Fixed Universal today.

https://www.youtube.com/watch?v=Ucs34BkfPB0

**Comment by koush** [comment] 2015-09-05 13:37
This is a WIndows 10 + Chrome issue. Fixed by packaging adb with Universal ADB (updated two days ago).

http://koush.com/post/universal-adb-driver

**Closed by koush** 2015-09-05 13:37 UTC
