### ISSUE TITLE
Cannot resize the UI of phone view

### ISSUE THREAD

**Issue by thebrightshade** [koush/vysor.io#505] opened 2020-05-07 19:04 UTC
**Describe the bug**
Cannot resize the window size of the phone view. This was working prior to the UI overhaul.

**To Reproduce**
1. Launch Vysor
2. Click on View for the device you want to view.
3. Try to resize the View window by clicking on the corner of the window and moving it.

**Expected behavior**
When the corner/edge of the window is clicked on and resized, the window should change in size.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version: 3.0.73

**Android (please complete the following information):**
 - Device: Non-Commercial Test Device
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/3e25620483bb2d5cbf89a75c91d3a9e4

**Vysor Bug Report**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment] 2020-05-07 22:36
screenshots or video please.

**Comment by koush** [comment] 2020-05-09 20:55
Closing unless I can get a screenshot or video. Can't reproduce.

**Closed** 2020-05-09 20:54 UTC
