### ISSUE TITLE
iOS: iMac 10.14.5，can not find iOS device

### ISSUE THREAD

**Issue by w4rw4r** [koush/vysor.io#717] opened 2021-02-09 04:34 UTC
Vysor version 4.0.17
iPhone 8 , iOS 13.6.1

Mac book 10.15.4, is ok, found , click
iMac version 10.14.5, can not find iPhone

please help

re:   try connecting the phone while locked, and unlock it after it is connected.

do not work

**Comment by stanleylhs** [comment] 2021-04-19 13:58
Koush said there is [issue prior to iPhone 8](https://github.com/koush/vysor.io/issues/745#issuecomment-821435672)?

I'm on Macbook Air with macOS 10.14.6 also can't find devices.

I have tested with iPhoneX, iPhone XSMax, iPhone 12, iPhone 12 mini.

Is it a 10.14 problem? Since the device management is moved from iTunes to Finder in 10.15?

**Comment by koush** [comment] 2021-04-20 04:02
> Koush said there is [issue prior to iPhone 8](https://github.com/koush/vysor.io/issues/745#issuecomment-821435672), so iPhone 8 seems to be find. Maybe a macOS problem.
> 
> I'm on Macbook Air with macOS 10.14.6 also can't find devices.
> 
> I have tested with iPhone X, iPhone XS Max, iPhone 12, iPhone 12 mini.
> 
> Is it a 10.14 problem? Since the device management is moved from iTunes to Finder in 10.15?

Try connecting the phone while locked, and unlock it after it is connected. Did this work for you?

**Comment by stanleylhs** [comment] 2021-04-20 07:46
Tried connecting while locked no luck.

**Comment by stanleylhs** [comment] 2021-04-22 11:36
Tried with macOS 10.15, iPhone 6S iOS 13, works correctly after clicking Trust in Finder.

**Comment by koush** [comment] 2021-04-22 17:02
> Tried with macOS 10.15, iPhone 6S iOS 13, works correctly after clicking "Trust" in Finder.
> 
> So will 10.14 be supported? Since it is the last version to support 32bit apps, lots of Mac are stuck there.
> Will be very nice to have 10.14 support.

Can you explain what you mean by "Trust" in Finder? I'm not familiar with that and would like to add that to the connection instructions.

**Comment by stanleylhs** [comment] 2021-04-22 18:23
> > Tried with macOS 10.15, iPhone 6S iOS 13, works correctly after clicking "Trust" in Finder.
> > So will 10.14 be supported? Since it is the last version to support 32bit apps, lots of Mac are stuck there.
> > Will be very nice to have 10.14 support.
> 
> Can you explain what you mean by "Trust" in Finder? I'm not familiar with that and would like to add that to the connection instructions.

In Finder Sidebar, under Locations, click the desired iOS device, then click "Trust"

![image](https://user-images.githubusercontent.com/4337525/115766245-56d61200-a3da-11eb-8663-215c69ea0fd4.png)

(This may be another issue, upon further testing, the mouse/pointer seems to be way off with iPhone 6S (unusable) and slightly off with iPhone 12. Will report another issue, when I have time.

**Comment by koush** [comment] 2021-04-22 19:02
I'm not sure if 32 bit will be supported, but I will be investigating it once it comes time to add support for native M1/ARM support.

As for the mouse/pointer, the mouse may be slightly off (because I can't send exact screen coordinates). You can recalibrate/reset on iPhone 12 by moving the mouse off screen, and then back over the mirrored iPhone.

iPhone 6 is very off because there are no default calibration values. You can provide x/y calibration values in Vysor Settings. If you find values that work well, please let me know, and I'll add them to Vysor via an update so it works out of the box. I do not have an iPhone 6 on hand to do this.

**Comment by stanleylhs** [comment] 2021-04-22 19:33
> I'm not sure if 32 bit will be supported, but I will be investigating it once it comes time to add support for native M1/ARM support.

Oh, for 32-bit support I don't mean Vysor, I mean 10.14 is the last macOS to support 32-bit for other legacy apps and drivers. So some production machines have to be stuck with 10.14 and won't upgrade to 10.15. So the key is to get Vysor to discover the "Trust" from iTunes, as per, 10.14 or below.

RE: mouse drift, will try it tomorrow when I have time. 12 mini seems to drift quite a bit too. Where do I put those settings? I just put them in the JSON file, right?

**Comment by koush** [comment] 2021-04-23 01:32
> > I'm not sure if 32 bit will be supported, but I will be investigating it once it comes time to add support for native M1/ARM support.
> 
> Oh, for 32-bit support I don't mean Vysor, I mean 10.14 is the last macOS to support 32-bit for other legacy apps and drivers. So some production machines have to be stuck with 10.14 and won't upgrade to 10.15. So it will be great if Vysor support 10.14! The key is to get Vysor to discover the "Trust" from iTunes, as per, 10.14 or below.
> 
> RE: mouse drift, will try it tomorrow when I have time. 12 mini seems to drift quite a bit too. Where do I put those settings? I just put them in the JSON file, right?

not the json settings, same place where encoder settings is. click the gear in the mirroring window.

**Comment by llune** [comment] 2021-04-27 11:13
Hi! Maybe I should make another issue but I've just downloaded the app to try it with iOS devices and I can't connect any iOS device with Vysor.

I'm on the last iOS version (iPhone 8 and iPad Pro 10.5 inch) and using MacOS Big Sur (11.2.2 (20D80)).

Otherwise it's working great with Android!

**Comment by koush** [comment] 2021-04-27 17:30
> Hi! Maybe I should make another issue but I've just downloaded the app to try it with iOS devices and I can't connect any iOS device with Vysor.
> 
> I'm on the last iOS version (iPhone 8 and iPad Pro 10.5 inch) and using MacOS Big Sur (11.2.2 (20D80)).
> 
> Otherwise it's working great with Android!

Sorry about this, I know exactly what you're talking about.
I've seen this issue and it's very difficult to track down and resolve. Here's what sometimes fixes it for me:

Disconnect the iOS device.
Lock it.
Close Vysor's main device list window.
Wait a moment.
Reconnect the iOS device.
Unlock it.

It should show up now. Sometimes I have to do this process several times.

I suspect the issue is some weird QuickTime device enumeration bug in the OS. Still investigating this.

**Comment by cbrevik** [comment] 2021-05-26 06:17
I've been having this issue with Vysor for some time now, my iOS device (iPhone XS, iOS 14.6, using macOS 11.2.3) is not found. This used to work earlier, but I'm not sure when it broke. I've tried the above steps several times over a couple of weeks, but it's not working. All other programs (like XCode, Finder, etc) seems to interact fine with the device.

**Comment by koush** [comment] 2021-05-26 07:45
> I've been having this issue with Vysor for some time now, my iOS device (iPhone XS, iOS 14.6, using macOS 11.2.3) is not found. This used to work earlier, but I'm not sure when it broke. I've tried the above steps several times over a couple of weeks, but it's not working. All other programs (like XCode, Finder, etc) seems to interact fine with the device.

Sometimes clicking reload fixes it. Or full quitting the Vysor app, and waiting a moment.

In any case, I'm in the middle of building out iOS support on the other OS builds. The upshot is that I'm no longer using the broken Apple Core Media APIs that results in no device being detected, and just talking to the USB Device directly. I'm hoping to release this in the coming weeks.

**Comment by koush** [comment] 2021-07-08 20:39
Fixed in stable channel.

**Closed by koush** 2021-07-08 20:39 UTC
