### ISSUE TITLE
The screen is being cropped out

### ISSUE THREAD

**Issue by dngo1996** [koush/vysor.io#132] opened 2016-03-18 00:27 UTC
Hello, I'm having an issue of whenever I connected my device to Vysor, the screen is being cropped out to the right. It's not showing all the android screen on the computer and no matter how much adjusting I'm doing (by re-sizing the vysor window), it's not going back to it center default view. Any ideas? Thanks

**Comment by scargill** [comment] 2016-03-18 08:27
I have exactly the same issue...  maybe 5% or so more on the right would be good.

**Comment by GENHEN** [comment] 2016-03-22 06:44
I want to give context about what is going on, so I provided a screenshot. It goes away if I uninstall/reinstall vysor in chrome, but not sure why it is happening consistently. It also seems to only occur when I leave my chrome on for a little too long or I open too many tabs. I suspect memory leak foul play

**Comment by jareboomafoo** [comment] 2016-04-07 15:58
I'm having the same issue. It's about 30-40px that are cut off.
![07-04-2016-11-57-51](https://cloud.githubusercontent.com/assets/3615202/14357776/0c1794a6-fcb8-11e5-9940-97ed16fd72de.png)

**Comment by andrewex** [comment] 2016-04-11 20:21
Same issue here. Would be nice if we could adjust the ratio.

**Comment by dopt** [comment] 2016-04-12 04:48
Same for my Note 3. Appreciated if developers can solve this.

**Comment by albertlua** [comment] 2016-04-14 22:10
I am also receiving the same issue. The curious thing is it's probably some kind of window issue. Taking a screenshot will take a screenshot of the whole screen correctly as show here:
![screenshot](https://cloud.githubusercontent.com/assets/18387795/14545318/bc3896b8-0263-11e6-9b7f-9395c3b7c62f.jpg)
While the window is cropped as shown above:
![capture](https://cloud.githubusercontent.com/assets/18387795/14545330/c7a4d8e0-0263-11e6-8881-776f26075d99.PNG)
Can't seem to get it to "glitch" into the right way.

**Comment by scargill** [comment] 2016-04-14 22:23
That right-and-side cutoff is quite annoying and I’m also finding the app crashes regularly leaving the screen fixes on whatever it was showing when crashed. This needs sorting. A potentially great app made into an annoyance because of a couple of minor bugs.

**Comment by dngo1996** [comment] 2016-04-21 22:24
Hey guys, just want to confirm, did any of you guy screen return to normal? My screen somehow magically returns back to it's default view today. Lets hope this minor bug is fixed.

**Comment by albertlua** [comment] 2016-04-22 00:49
Nope, still the same for me.

**Comment by koush** [comment] 2016-05-08 21:54
Are you all on windows?

**Comment by GENHEN** [comment] 2016-05-09 00:48
I don't know about anyone else, but I get the same problem when I use vysor on ubuntu as well as windows

**Comment by albertlua** [comment] 2016-05-09 01:23
Indeed on Windows 10.

**Comment by dngo1996** [comment] 2016-05-09 09:20
My screen has been normal for the past 2 weeks (tested with two devices, both normal view now), the issue resolve itself when my google chrome update from 49.0.2623.110 to 50.0.2661.87 (currently on 50.0.2661.94 version). I don't know if this will help you guys, just want to share what I know. Also, I'm a Window 10 user.

**Comment by albertlua** [comment] 2016-05-10 02:28
The issue has been resolved with version 50.0.2661.94 of Chrome for me.

**Comment by jareboomafoo** [comment] 2016-05-11 19:08
Yep. Just updated chrome on windows and the issue is corrected now.

**Closed** 2016-05-12 18:55 UTC
