### ISSUE TITLE
Error: Invalid Package - electron.asar

### ISSUE THREAD

**Issue by cmptrgeek** [koush/vysor.io#889] opened 2021-08-03 17:06 UTC
This morning when I went to use Vysor, I am suddenly getting an invalid package error referencing electron.asar. Not sure what has happened as it was working fine yesterday and no updates were loaded onto my PC. I have tried uninstalling and reinstalling Vysor to no avail.

My OS info:

- Edition	Windows 10 Pro
- Version	21H1
- Installed on	‎5/‎24/‎2021
- OS build	19043.1110
- Serial number	PC0MQF11
- Experience	Windows Feature Experience Pack 120.2212.3530.0

![2021-08-03_13-01-40](https://user-images.githubusercontent.com/3318373/128056550-66a40614-803d-47a4-98d4-f47cbf7618c8.png)

**Comment by koush** [comment] 2021-08-03 17:07
Generate a bug report please

**Comment by koush** [comment] 2021-08-03 17:08
Might want to try just clicking the reload vysor too.

**Comment by cmptrgeek** [comment] 2021-08-03 17:11
https://gist.github.com/ae54e29ca875c611097107ecbc46ae2b

**Comment by koush** [comment] 2021-08-03 17:31
You need to capture a bug report while that window is open showing the error. Please follow the instructions to generate a bug report.

**Comment by cmptrgeek** [comment] 2021-08-03 18:26
https://gist.github.com/568cac1adbeca72e1aa38d790f167650

[ff17a4fa-7114-4d2a-838a-0b58d957ef82.txt](https://github.com/koush/vysor.io/files/6926309/ff17a4fa-7114-4d2a-838a-0b58d957ef82.txt)

**Comment by koush** [comment] 2021-08-03 18:57
Try installing this manually:

https://electron.vysor.io/Vysor-release.apk

**Comment by koush** [comment] 2021-08-03 18:59
I see this is a custom android device. For whatever reason, adb install does not work on that device, its failing in the Android framework with some error that I can't map back to the android open source project, because they've modified it. You'll need to side load the APK yourself somehow to resolve this.

**Comment by koush** [comment] 2021-08-03 18:59
Only official Google Play or Amazon devices (that pass the compatibility test suites) are supported.

**Comment by cmptrgeek** [comment] 2021-08-03 20:05
I have been using Vysor for months with these devices, so why all of a sudden is it not working? I use adb with these devices and was able to side load the file you sent a link for. Once I side loaded the apk, Vysor worked again.

**Comment by koush** [comment] 2021-08-03 20:44
A vysor APK update triggered a new apk install.

**Comment by koush** [comment] 2021-08-03 20:48
what version of android is this? you really gotta include all the information correctly.

**Comment by koush** [comment] 2021-08-03 20:49
You must attach a Vysor Bug Report Link

First, trigger the bug.
Leave the window with the bug open. Do not close it, or the bug data will be lost.
To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED. The bug report contains internal logging from the app.
To Reproduce Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior A short description of what you expected to happen.

Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. MacOS 11.4.10]
Android (please complete the following information):

Device: [e.g. Pixel 4]
OS: [e.g. Android 10]
Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]
Additional context Add any other context about the problem here.

**Comment by koush** [comment] 2021-08-03 20:50
Fill that out properly and I'll look into it more.

**Closed** 2021-08-04 20:37 UTC
