### ISSUE TITLE
The share button is not responding

### ISSUE THREAD

**Issue by brozikcz** [koush/vysor.io#628] opened 2020-09-15 08:07 UTC
While using Vysor, I tried to get the link, but the share button didn't work. And when I receive a link from the other user and  use it the connection does not work.

https://gist.github.com/VysorLogs/5df374fb0970e987568d2778998af56e

![image](https://user-images.githubusercontent.com/3849376/93183645-8aadd280-f73b-11ea-9ddc-9a875710643a.png)

OS: MacOS 10.15.6
Vysor: 3.2.8
Device: Samsung S10e, Android 10

**Comment by koush** [comment] 2020-09-15 08:58
Fixing.

**Comment by koush** [comment] 2020-09-15 09:37
Initial investigation shows that GAE is starting to fail after around 3000 concurrent connections. This is a result of a server migration to GAE from my own physical infrastructure.

I'll need to modernize the push transport to use Web Push where available, and also improve the existing socket.io service.

Might take a day or two.

**Comment by koush** [comment] 2020-09-16 01:23
Please verify the fix in 3.2.11.

**Comment by brozikcz** [comment] 2020-09-16 06:46
Still nothing...

https://gist.github.com/VysorLogs/529f1fbb4af4a85e3312b04769602a6d

**Comment by koush** [comment] 2020-09-16 07:45
Thanks for testing. I've added more logging and fixed some race conditions around the new push channel. Can you try again on 3.2.13?

**Comment by brozikcz** [comment] 2020-09-16 13:18
Share button isn't still responding.
https://gist.github.com/VysorLogs/135e396b3359c80239fe5db4ecc5e8f6

**Comment by koush** [comment] 2020-09-16 18:45
Thanks, I found further issues in your logs that may be addressed by 3.2.14.

```
credentials [object Promise]
credentials/listening error Error: Missing gcm object in credentials
```

**Comment by koush** [comment] 2020-09-16 18:46
Looks like it got saved in a buggy state, so resetting it and then allowing it to update may resolve it. Though it should also automatically clear bad settings now too.

**Comment by brozikcz** [comment] 2020-09-17 07:21
The streaming doesn't work but I can connect via ADB (adb -s 127.0.0.1:49240 shell) to the remote device.

Client side (reciever):
https://gist.github.com/5231969deaa86b4b9c938167786a6aab

Server side:
https://gist.github.com/588b9b7249578ce09a7ee12188f7f484

**Comment by koush** [comment] 2020-09-17 08:58
Thanks, I finally reproduced your underlying issue.

In the meantime, instead of pasting the link into the browser clicking "Open WIth Vysor" when prompted, click "Connect Network Device" and paste in the link.
![Vysor](https://user-images.githubusercontent.com/73924/93449207-547e6900-f889-11ea-9d1d-094ce8afe11d.png)

**Comment by brozikcz** [comment] 2020-09-17 10:43
When I inserted the link directly into dialog so I'm stucked on the "connecting to remote device".

https://gist.github.com/81e96efd81919fdd26878fb9b025aceb

**Comment by koush** [comment] 2020-09-23 17:46
Can you try checking again on the latest version?

**Closed** 2020-10-23 06:03 UTC
