### ISSUE TITLE
Copy paste bug

### ISSUE THREAD

**Issue by timeakesmarky** [koush/vysor.io#432] opened 2020-01-21 18:28 UTC
Copying a line with special characters and pasting in Vysor doesn't work.
For example, "Ksuradhâra Kunda"
Or copying a line with special characters in between.

And there seems to be a limit on the number of characters that can be pasted.

**Comment by Heretushi** [comment] 2020-01-21 22:44
Hi there, on my setup, the phrase "Ksuradhâra Kunda" works. I copied a lot more characters successfully.

**Comment by Heretushi** [comment] 2020-01-21 22:52
https://imgur.com/SCU2Og4

As you can see there, I selected a large part of text from this page and pasted it in Keep.

**Comment by timeakesmarky** [comment] 2020-01-21 23:13
From computer to Vysor?

**Comment by Heretushi** [comment] 2020-01-21 23:15
Yes. From my computer to Vysor.
Is the contrary possible ?
I tried to copy text from Vysor and it did not paste into my computer.

**Comment by koush** [comment] 2020-01-22 05:38
@timeakesmarky i think you'll need to enable the "international keyboard" option to paste special characters. Let me know if that works.

**Comment by koush** [comment] 2020-01-22 06:09
@Heretushi it was possible in older versions of android, but something broke it in recent versions. I'll need to investigate and fix it, if possible.

**Comment by Heretushi** [comment] 2020-01-22 13:04
I did some investigation on my side to try to reproduce the problem without international keyboard.

1. Reset both Vysor (incl. killing any stray ADB.exe process) **and** phone.
2. Plugging phone in USB. Unlocking so Vysor won't reset abruptly.
3. Launching Vysor.
4. Making sure International Keyboard is OFF.
5. Clicking "View" on Pixel 3.

- There was NO "Installing Vysor APK" in the Windows.
- Clicking on a text field opened the Gboard keyboard and NOT the Vysor Keyboard.
- Manually switching to Vysor from the keyboard selection menu was possible (no crash).
- Accented characters are recognized.

This is not the behavior I was expecting. I expected : 

- Vysor to be active upon connection.
- Accented characters to be unavailable.

I am unable to proceed further for now. I will try to reset the Vysor Android App and retry the procedure.

**Comment by Heretushi** [comment] 2020-01-22 13:26
In trying to continue investigating this issue, I reseted and uninstalled Vysor from my computer.

Upon reinstallation, I can't get it to update to the latest version. Vysor does warn me of a new version, I click on "Restart" to get the update and when it comes opens, it's still at version 2.1.7. 

No matter how many times I close and open the program, it won't update to 2.2.5.

I am now stuck with an unusable Vysor setup since the keyboard won't send keys to my phone. :/

**Comment by Heretushi** [comment] 2020-01-22 14:51
Try #2.

Setup :

- Phone plugged in and unlocked.
- Vysor android app storage was cleared (Clear storage in app info).
- Desktop Vysor is closed and no stray ADB process run.

1. Launch Vysor on desktop.
2. Make sure International Keyboard is OFF.
3. Click "View" on phone.

- There was NO "Installing Vysor APK" in the Windows.
- Clicking on a text field opened the Gboard keyboard and NOT the Vysor Keyboard.
- Manually switching to Vysor from the keyboard selection menu was possible (no crash).
- Accented characters are recognized.

So the behavior is exactly the same as before I reset everything and still not correct. The correct behavior I expected :

- Vysor to be active upon connection.
- Accented characters to be unavailable.

**Comment by Heretushi** [comment] 2020-01-22 14:54
Related to this issue, after my previous test, I was still able to copy/paste a ton of text from my computer to the phone via Vysor.

It is the expected behavior since international keyboard seems always active in my case.
Given the observed behavior of Vysor in my setup, I cannot test without international keyboard being active.

**Comment by Heretushi** [comment] 2020-01-22 15:07
Video of international keyboard working even though the option is turned off.


http://imgur.com/gallery/jiK1fDh

**Comment by koush** [comment] 2020-01-23 20:15
I have a fix for copying from Android and pasting to PC coming. Android 9/10 broke some internal APIs.

**Comment by koush** [comment] 2020-01-23 20:22
Fixed in 2.2.6.

**Closed by koush** 2020-01-23 20:22 UTC

**Comment by koush** [comment] 2020-01-23 20:26
@timeakesmarky 
There may be multiple copy and paste issues here. So if this did not resolve your issue, please create a new one. I believe your character issue requires that you use the international keyboard.

**Comment by timeakesmarky** [comment] 2020-01-23 20:27
Sure, my phone died after a long time. I'll test soon. Thanks!
