### ISSUE TITLE
Device window isn't showing

### ISSUE THREAD

**Issue by AlaaZarifa** [koush/vysor.io#625] opened 2020-09-13 10:00 UTC
**Describe the bug**
When I click on the "VIEW" button of my device, I expected a window of the device to show, but it didn't', although it is showing in the taskbar. when I click on it from the taskbar, nothing happens.! I tried reloading Vyson and restarting my PC, but the problem still persists. 

**Attach a Vysor Bug Report Log**

I can't generate a log report if the window isn't showing...!!!
 
**Screenshots**
 
  
![image](https://user-images.githubusercontent.com/18426012/93015277-d5570f80-f5c0-11ea-8be8-740ed7998653.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Vysor Version 3.2.5

**Android (please complete the following information):**
 - Device:  Pocophone F1
 - OS:  Android 10x
 - Vysor Bug Report Link:  I can't generate a log report if the window isn't showing...!!!

**Comment by koush** [comment] 2020-09-13 18:31
are you on a laptop or some system that has multiple monitors? The window somehow ended up off screen and the position was saved there. I'll fix this. In the meantime, clicking "reset" and logging back in will resolve this issue.

**Comment by koush** [comment] 2020-09-13 18:31
duplicate of https://github.com/koush/vysor.io/issues/507

**Comment by AlaaZarifa** [comment] 2020-09-15 08:21
@koush Yes, sometimes I plug my laptop to a second monitor, and sometimes I just unplug the cable and continue using just the laptop. I guess that what causes the problem. 

Thanks for the workaround. waiting for the final fix.

**Comment by koush** [comment] 2020-10-23 06:05
tracking this already as a duplicate https://github.com/koush/vysor.io/issues/507

**Closed by koush** 2020-10-23 06:05 UTC
