### ISSUE TITLE
Vysor Pro update from earlier this week will not push updated apk

### ISSUE THREAD

**Issue by dbjherbert** [koush/vysor.io#857] opened 2021-07-16 15:38 UTC
I use Vysor to wirelessly connect to 3 Android TV devices on a daily basis.  These connections were working fine earlier this week.

Today, it seems a new version was loaded (Message about trying out the new Codec at the top of the device Window)
I connect to the Device using the IP Address as usual - connection succeeds
Launch the View Wirelessly or View Device
Device Window opens up and it seems to try to uninstall the Vysor apk
Then: _"Connection Error:  Error Connecting to Android Device Error: did not receive adb socket host okay (Retry / Cancel)"_ 
I can use adb from the command line to connect, issue commands and disconnect

Devices are running Android 9.  Desktop app on MacOS Big Sur 11.4 (Mac Book Pro 2019)
Vysor apk is no longer installed on any of the devices.
Developer Mode enabled (Again, adb connection succeeds.)

<img width="888" alt="Screen Shot 2021-07-16 at 11 35 52 AM" src="https://user-images.githubusercontent.com/31732704/125973069-6c5a4956-6205-4436-aeb6-2ea853478cf9.png">

**Comment by koush** [comment] 2021-07-16 16:56
Can you try running:

```
adb kill-server
```

That will terminate your existing adb connection and force a restart.
Also, please include a generated bug report.

**Comment by dbjherbert** [comment] 2021-07-16 17:24
Ran it, retried, same error

Bug Report:

https://gist.github.com/9c37487d45b41bdb69eba2be22383354

**Comment by koush** [comment] 2021-07-16 17:28
The log shows you trying to mirror an iOS device, not an Android device?

**Comment by dbjherbert** [comment] 2021-07-16 17:36
Thats weird.  No, they are Android devices.  Notice Screen shot shows Pyxis/AFTMM device connected in Android.
<img width="770" alt="Screen Shot 2021-07-16 at 1 36 07 PM" src="https://user-images.githubusercontent.com/31732704/125987239-6d721925-3cad-4f6c-ba97-2100b8d7b8dc.png">

**Comment by koush** [comment] 2021-07-16 17:37
Can you generate a new bug report after encountering the error and send that again?

**Comment by koush** [comment] 2021-07-16 17:37
Oh wait had my tabs mixed up and was looking at something else. One moment.

**Comment by koush** [comment] 2021-07-16 17:39
Ok, I see you're on the beta site and using the new APK I rolled out last night. Seems there's issues with that (I was testing some stuff). Let me roll it back. One moment.

**Comment by koush** [comment] 2021-07-16 17:40
Appreciate you being on the beta channel! It helps me track down stuff like this before I put it on stable 😄

**Comment by dbjherbert** [comment] 2021-07-16 17:42
I was on Release, but after the issue I saw in another report that Beta might fix it ;) Guess I forgot it there...Thanks for the quick responses!

**Comment by koush** [comment] 2021-07-16 17:51
Couple things to try, in order, on the beta channel:

1. Reload Vysor to trigger an update to 4.1.58. Use the new Force Restart ADB Server button. This has some more logging around the failure, and also reverts back to the regular non-shrunk APK.
2. If that does not work, Install the prerelease which comes with a newer version of ADB: https://github.com/koush/vysor.io/releases/tag/v4.1.56

**Comment by dbjherbert** [comment] 2021-07-16 17:59
1. Updated and reloaded.  Same error:
https://gist.github.com/5a35cb0be06ddff1f6da1c6daf42ba93
<img width="1029" alt="Screen Shot 2021-07-16 at 1 54 43 PM" src="https://user-images.githubusercontent.com/31732704/125989496-28cc5ec3-705b-404a-b413-eb8cd4d7c7c5.png">

2. Same problem:
https://gist.github.com/1a84baabd3f44a3126451e7f74caf9ea
<img width="1286" alt="Screen Shot 2021-07-16 at 1 58 10 PM" src="https://user-images.githubusercontent.com/31732704/125989773-9c01f8d3-06c0-4aae-a775-051ea288bcb0.png">

**Comment by koush** [comment] 2021-07-16 18:06
It seems to be failing on the push of the apk. Could be due to two reasons: not enough space or the directory it is expecting does not exist.

Run the following please:

```sh
adb shell 'ls -l /data/local/tmp ; df -h'
```

**Comment by dbjherbert** [comment] 2021-07-16 18:25
total 19292
-rw-rw-rw- 1 shell shell 4945497 1969-12-31 19:00 apk1618242343868.apk
-rw-rw-rw- 1 shell shell 4945853 1969-12-31 19:00 apk1618928217206.apk
-rw-rw-rw- 1 shell shell 4948693 1969-12-31 19:00 apk1620823503011.apk
-rw-rw-rw- 1 shell shell 4886584 1969-12-31 19:00 apk1623852504527.apk
-rw-rw-rw- 1 shell shell       8 1969-12-31 19:00 vysor.pwd
Filesystem          Size  Used Avail Use% Mounted on
/dev/root           1.4G  1.2G  222M  86% /
tmpfs               995M  476K  994M   1% /dev
tmpfs               995M     0  995M   0% /mnt
/dev/block/odm       31M  464K   30M   2% /odm
/dev/block/product  122M   89M   30M  75% /product
/dev/block/dm-1     244M  133M  106M  56% /vendor
/dev/block/data     4.1G  1.2G  2.8G  31% /data
/dev/block/cache    582M   17M  547M   3% /cache
/dev/block/metadata  11M   40K   11M   1% /metadata
/data/media         4.1G  1.2G  2.8G  31% /storage/emulated

**Comment by koush** [comment] 2021-07-16 18:29
If you manually side load this, it should get you past the installation issue. I'll need to investigate this further.

https://electron.vysor.io/native/android/Vysor-release.71920051156fa68fa16cfeff5eceedb44ed6f82f27f942f9422132872ce56fc6.apk

**Comment by koush** [comment] 2021-07-16 18:30
Also, please reload and get me one final log on v4.1.59.

**Comment by dbjherbert** [comment] 2021-07-16 18:38
Interesting issue.  Older version of Platform-tools would not install:
➜  platform-tools-OLD ./adb version
Android Debug Bridge version 1.0.41
Version 31.0.1-7187441
Installed as /Users/duaneh/platform-tools-OLD/./adb

➜  platform-tools-OLD ./adb install Vysor-release.71920051156fa68fa16cfeff5eceedb44ed6f82f27f942f9422132872ce56fc6.apk
Performing Streamed Install
adb: failed to install Vysor-release.71920051156fa68fa16cfeff5eceedb44ed6f82f27f942f9422132872ce56fc6.apk: %




➜  platform-tools 2 ./adb install Vysor-release.71920051156fa68fa16cfeff5eceedb44ed6f82f27f942f9422132872ce56fc6.apk
Performing Streamed Install
Success
➜  platform-tools 2 ./adb version
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
Installed as /Users/duaneh/platform-tools 2/./adb


The new APK resolved the issue.

With the issue still on another device, I generated a new Bug Report:
https://gist.github.com/9e47630d4453ef32f744e874c4bcd7cf

**Comment by koush** [comment] 2021-07-16 19:00
Vysor packages the following version in the prerelease:
```
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
Installed as /Volumes/Dev/Vysor/Chrome/web/public/native/darwin/adb
```

If you used the "Restart ADB Server" button, it should have started that one. What else do you have running that would start ADB? Android Studio?

**Comment by dbjherbert** [comment] 2021-07-16 19:09
Colleague just had the same issue, old adb would not install the apk you shared, updated version did...

Tried my last device.  Restarted Vysor and Force Restarted ADB (Runtime 4.1.56) - still won't update the apk on the device - same error

I have Android Studio, but it's not running.

Latest:
https://gist.github.com/ad1a2d7cca11fbbc51faeea364613a43

For now, I am working.  Thanks for your help, happy to help test any time. (duane.herbert@gmail.com)

**Comment by koush** [comment] 2021-07-16 19:46
I downloaded that exact adb and attempted and installation on the Pixel 4, and it succeeded. Could you describe your test TV devices? What android OS version, model, etc?

**Comment by dbjherbert** [comment] 2021-07-16 20:05
Two of the devices are Tivo AndroidTV Set Top Boxes made by SEI, one is a 4K Tivo Streaming Stick and another was an AmazonFireTV 4K stick.  Tivo boxes running Android , Amazon with their FireTV OS.
All have them have been working flawlessly till now.

**Comment by koush** [comment] 2021-07-16 20:14
Understood. It's likely an adb daemon/client issue that was triggered by the recent Vysor update when it required a new APK to be installed. The buggy one you encountered was released in March, but Vysor has not updated the APK in ~6 months, until this past week.

Investigating workarounds now.

**Comment by koush** [comment] 2021-07-16 20:58
This might be resolved in 4.1.60 on the beta channel, if you don't mind confirming. I changed the adb install process to use a streaming install vs push + install.

**Comment by dbjherbert** [comment] 2021-07-19 12:42
Running Pro version 4.1.63 (Runtime 4.1.62), restarted and reconnected to the device.  Uninstalled Vysor client and tried to connect.  Fails with same error as before.
https://gist.github.com/60b148291ce7c48f2093617c1d20bfcc

**Comment by koush** [comment] 2021-07-19 16:27
Unfortunately that log does not contain the information I need. Seems there was an error during the log generation. Can you click Reload Vysor, kill adb (via the new option in Vysor's main list), and try again? Please ensure you leave the failed window open so those errors don't get lost on window close.

Internally now, Vysor has the latest adb (the one that works) and simply uses the adb install command to install it.

**Comment by koush** [comment] 2021-07-19 17:09
Extremely weird. This is what it is running internally, can you try it in a command line?

```sh
/Applications/Vysor.app/Contents/Resources/app.asar.unpacked/native/darwin/adb -s 192.168.0.190:5555 install /var/folders/sr/nmwrfs89037gxk6153tnw4fw0000gp/T/tmp-53679-XGzYoNuzFmjc-.apk
```

**Comment by koush** [comment] 2021-07-19 17:10
That tmp apk file may not exist anymore if you've closed the app, but you can reproduce the error, and generate another log to get the location of the new tmp file.

**Comment by dbjherbert** [comment] 2021-07-19 17:11
```
➜  platform-tools 2 /Applications/Vysor.app/Contents/Resources/app.asar.unpacked/native/darwin/adb -s 192.168.0.190:5555 install /var/folders/sr/nmwrfs89037gxk6153tnw4fw0000gp/T/tmp-53679-XGzYoNuzFmjc-.apk
Performing Streamed Install
Success
➜  platform-tools 2
```

Seemed to work, I can view.

**Comment by koush** [comment] 2021-07-19 17:49
I'll need to add more logging and push more update. Even the adb binary command in the log is failing with no reported error:

```sh
adb: failed to install /var/folders/sr/nmwrfs89037gxk6153tnw4fw0000gp/T/tmp-53679-XGzYoNuzFmjc-.apk: 
```

**Comment by koush** [comment] 2021-07-19 18:12
Do you have a wired USB device on hand to verify this issue with? I want to eliminate the possibility that this is happening due to adb over tcpip. I tested the tcpip path myself, but did not encounter this problem.

**Comment by koush** [comment] 2021-07-19 18:41
I released 4.1.64 into the beta channel which has a change with how a file is pushed prior to the adb installed. Also added a bunch more logging. Let me know if that works.

**Comment by dbjherbert** [comment] 2021-07-19 19:01
Unfortunately no USB port on these devices to plug straight in.
Tried with new version:
https://gist.github.com/VysorLogs/2ec617ef698c2a212e122f64b3e0ce10

**Comment by koush** [comment] 2021-07-19 19:09
Understood, do you have a normal Android phone to check?

**Comment by koush** [comment] 2021-07-19 19:13
Sending you an email to set up a Vysor Share session to remotely diagnose this problem.

**Closed** 2022-04-16 01:19 UTC
