### ISSUE TITLE
Window resizing or position fixing / size fix

### ISSUE THREAD

**Issue by V3r0x** [koush/vysor.io#34] opened 2015-08-27 13:23 UTC
![unbenannt](https://cloud.githubusercontent.com/assets/1812767/9521523/af4f725e-4ccf-11e5-8be6-c32911c8a71b.PNG)
Hi,
using W10 and LG G2.
I have issues that the window is resizing in weird ways. When it originally started up the display was crisp like on the phone itself. When i dragged the window the first time it resized and got to a screen size of maybe FullHD resolution and is exceeding the limits. now i can't get it back to "normal".

thanks, great app so far.

**Comment by koush** [comment] 2015-08-27 16:50
ok, will fix this.

**Comment by koush** [comment] 2015-08-27 16:51
duplicate of
https://github.com/koush/vysor.io/issues/9

**Closed by koush** 2015-08-27 16:51 UTC

**Comment by V3r0x** [comment] 2015-09-07 13:52
works now. But still i'm searching Titlebars, and extra resizing options. It still happens that the display is set to native phone resolution when automatically resizing. A fixed size in the connection window would also hurt noone and let the window stay small .....
