### ISSUE TITLE
"International Keyboard" problem

### ISSUE THREAD

**Issue by NezihEge** [koush/vysor.io#736] opened 2021-03-13 09:05 UTC
I use your app and it is perfect. It really stinks of labor, but I have a problem. When I open the "International Keyboard" option in the settings, I can use some Turkish letters but sometimes I cannot use it. What is the reason for this?
The letters I want to use are letters like "ğ, ü, ş, İ, ç, ö". It can be used sometimes, but sometimes I cannot. I think I noticed something: When I slide the phone's notification bar, I can't use again Turkish letters if I choose another keyboard instead of Vysor, even for once from the "Select Your Keyboard" section. I choose the again Vysor keyboard, but it is broken, I cannot use Turkish letters. Even now the problem still continues, and I don't know how to solve it.

P.S.:I used Google Translate in some places, I hope I could explain myself. Sorry for tiring you, have a nice day :)

**Comment by koush** [comment] 2021-03-13 19:19
Are you on Windows by chance?

**Comment by koush** [comment] 2021-03-13 19:21
Can you provide a video of this "slide the notification bar"? I think that would help quite a bit in understanding what the issue is. Can record the video using Vysor and upload to YouTube, etc.

**Comment by NezihEge** [comment] 2021-03-14 07:35
Yes, i'm user of windows 10.
The problem still continues. I cannot use the letters "ğ, ü, ş, İ, ö". 

This is youtube link: https://youtu.be/u0MtsEHoNkQ

**Comment by NezihEge** [comment] 2021-03-14 07:48
_

> "_The problem still continues. I cannot use the letters "ğ, ü, ş, İ, ö"._

_
As you can see from the end of the video, the problem actually does not persist: D

**Comment by NezihEge** [comment] 2021-03-14 09:12
Update: This time I did nothing. The problem started again, I can't use letters.

**Comment by dieskim** [comment] 2021-03-24 01:54
@NezihEge  - I have had many problems with the International Keyboard in the past - see #684 and #555 
Currently the best way for me seems to be to FORCE STOP the app on the phone - then wait a min and then set the phone back to the Vysor Keyboard

**Comment by NezihEge** [comment] 2021-03-25 14:27
> @NezihEge - I have had many problems with the International Keyboard in the past - see #684 and #555
> Currently the best way for me seems to be to FORCE STOP the app on the phone - then wait a min and then set the phone back to the Vysor Keyboard

Yeah! I guess that solves the problem. I still could not use the letters. I did Force Stop and it started running.
Thanks :)
I will report the latest news, I have no idea if we can solve the problem exactly this way, because sometimes it gets better on its own .For now, this is how the problem is solved.

**Comment by NezihEge** [comment] 2021-03-26 23:31
Yeah! I guess that solves the problem. I still could not use the letters. I did Force Stop and it started running.

**Comment by koush** [comment] 2021-04-27 05:56
I believe this is fixed in 4.0.36.

**Closed by koush** 2021-04-27 05:56 UTC
