### ISSUE TITLE
[Suggestion] Remember window size and position

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#433] opened 2020-01-22 12:49 UTC
**Describe the bug**
When Vysor initialize it resets its position to the center of the screen.

**To Reproduce**
1. Start Vysor.
2. Plug in Android Device.
3. Click "View".
4. Main Vysor window opens in the center of the screen.

Alternative steps to reproduce the behavior:
1. Vysor is opened and device is unplugged (sad computer is showing).
2. Plug in Android Device.
3. Vysor screen initializes, moves from current position to the center of the screen.

**Expected behavior**
Vysor would keep last used size and position.

**Screenshots**
On demand.

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Vysor Pro Version 2.2.5

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link: not necessary.

**Vysor Bug Report**
I prefer to not use that feature since bug reports contain MORE than the email. It contains all associated information from your subscription including home address.

**Android Logcat**
On demand.

**Additional context**
I prefer to not use the term "Feature **request**" since I'm in no position to request anything. It would just be a really neat quality of life improvement.

**Comment by koush** [comment] 2020-01-22 19:55
This actually is the default behavior already.
Vysor will recenter itself if it think the window is offscreen during startup.
Multiple monitors?

**Comment by Heretushi** [comment] 2020-01-22 20:22
Yes, multiple monitor! :)

I did try with only one monitor and while the window does not reset exactly to the screen center, it does shift around quite a bit, requiring me to snap it back to the side.

To place the Vysor main window in Windows 10, I use its "snap to side" feature. It will resize the Vysor main window to take half the screen, then sometimes Vysor will take on itself to resize it's main window to the actual aspect ratio required (and sometimes not).

**Comment by koush** [comment] 2020-01-23 00:37
I'll need to look into this. Vysor currently enforces the phone aspect ratio. There's likely some strange interaction happening with the snap to screen.

**Comment by Heretushi** [comment] 2020-01-23 01:43
Just to be sure we're on the same page : I enjoy Vysor enforcing the aspect ratio. It's a feature I want and enjoy. I'm not happy when it does not automatically resize the window. In these cases, I need to manually resize the window just by a tiny amount and Vysor will then enforce the aspect ratio.

But then, the main problem still persist : when unplugging then plugging the phone again, the Vysor window will go back straight to the center of the screen.

My uneducated guess : if Vysor reset the window because it's "out of bound", snapping to the side need to enforce a smaller Y dimension since the bottom menu bar of Vysor is always under the Windows Menu. This might cause the behavior since Vysor will detect that it's bottom menu is blocked.

**Comment by Heretushi** [comment] 2020-02-12 20:12
Just doing a check-up. Do you need any more information on this matter ? I still can reproduce the behavior 100% of the time.

Thanks.

**Comment by koush** [comment] 2020-02-14 19:02
I'm still aware of the issue. I'm currently working on other Vysor features to mitigate the deprecation of Chrome apps.

**Comment by Heretushi** [comment] 2020-03-27 15:20
Just a friendly check-up on this issue that I'm having every day.
Since the time I posted, I had the occasion to test the issue using a SINGLE SCREEN and it's still happening.
So I can confirm it happens on a DUAL screen setup and a SINGLE screen setup.

I am still convinced it could be linked to my previous comment :

> My uneducated guess : if Vysor reset the window because it's "out of bound", snapping to the side need to enforce a smaller Y dimension since the bottom menu bar of Vysor is always under the Windows Menu. This might cause the behavior since Vysor will detect that it's bottom menu is blocked.

Thanks.

**Comment by koush** [comment] 2020-04-15 05:58
I have a fix for this coming. I worked on this as part of the major rewrite.

Can you try the new progressive web app beta here (it's installable to the desktop):
https://app.vysor.io
I want to verify this is fixed.

Native apps coming soon.

**Comment by Heretushi** [comment] 2020-04-15 12:34
Hey! Thanks for the heads up.
I did try the progressive web app, but I can't view the phone. 

I connect my phone with the USB cord.
I click "Connect Android USB Device".
It's detected as an available device.
I select the phone to connect.
It's listed in the "available devices" but without a Serial number.
When I click "View", nothing happens.

Disabling every kind of adblocking/flashblocking/extension did not help.

**Comment by koush** [comment] 2020-04-15 14:12
What phone? Anything in the JavaScript console? Chrome browser I presume?

**Comment by Heretushi** [comment] 2020-04-15 16:35
- Pixel 3.
- How do I access the javascript console ?
- Chrome, indeed.

**Comment by Heretushi** [comment] 2020-04-15 16:38
So, for whatever reason, it works now. :| :|

**Comment by koush** [comment] 2020-04-15 18:44
Actually reproing this bug, the positioning isn't saved on the PWA unless the window is resized (there's no window events for browser window movement).
The native app, it is fixed.

**Comment by koush** [comment] 2020-04-15 18:46
actually, should just be able to poll for the screenX/Y values.

**Comment by Heretushi** [comment] 2020-04-16 00:27
I hope you are leaving comments for yourself. Otherwise, not sure how I should help. :)

**Comment by koush** [comment] 2020-04-16 00:54
Yeah, they are for myself haha

**Comment by koush** [comment] 2020-05-01 00:53
Hey, can you check if the issue is resolved in the prerelease downloads?
I also fixed most of the window docking issues.

electron window state is still a bit weird, and it doesnt report that the window is docked. so if you fullscreen/maximize, it won't freak out. but if you dock half the screen, vysor will continue trying to snap to fit.

**Comment by Heretushi** [comment] 2020-05-01 12:22
Hey Koush, I tested with the 3.0.44 Chrome App.

So, first thing first : Vysor do keep position when unplugging/plugging. So that's that. Thanks you! :)

NEW BUG (Lets call this bug : "Left edge Stick") : the windows does not fully snap to the side of the screen. There a gap between some sides of Vysor and the edges of the screen area. From my observation, it goes : 

1. I click my mouse and drag Vysor to the left side of the screen.
2. Windows 10 detects that I want to snap Vysor to the left side of the screen.
3. Windows 10 show me how it will extend Vysor to cover the complete left half of the screen (stuck to the 3 edges -- upper, left and lower edges).
4. I unclick the mouse. Windows 10 extends Vysor as it was showing me.
5. Vysor realizes it no longer has the proper aspect ratio.
6. Vysor enforces the proper aspect ratio while sticking the upper edge of the screen (no gaps created).
7. Vysor creates a gap between its side and the left and lower edges of the screen area.

End result : https://imgur.com/a/JepFJeg (first image)

NEW BUG (Let's call this bug : "Right Edge Stick") : when trying to stick Vysor to the right half of the screen, the same aspect ration enforcing operation occurs and Vysor is stuck floating nowhere near the right edge of the screen. :)

End result : https://imgur.com/a/JepFJeg (second image)

Thanks for your hard work and awesome communication. Appreciated.

**Comment by koush** [comment] 2020-05-01 17:54
Hmm ok will check windows. I didn’t know windows could dock. I’m a Mac user.

**Comment by Heretushi** [comment] 2020-05-01 17:58
NP mate, that's why I'm here to help you. Let's get this situation sorted as a team. :) 👍

**Comment by Heretushi** [comment] 2020-05-04 14:20
Hey Koush, since I now had the capacity to install the NATIVE app (I'm no longer using the PWA), I can confirm the "Left Edge Stick" bug as PWA exclusive. It does not affect the native app.

The "Right Edge Stick" bug is still there for NATIVE app.

**Comment by Heretushi** [comment] 2020-05-04 14:31
I will open a new bug for the Right Edge Stick. This position and size is fixed. :) Thanks a lot Koush.

**Comment by iamscottweber** [comment] 2021-04-16 13:55
This seems to be an issue again in version 4.0.33

**Comment by koush** [comment] 2021-04-16 18:33
> Remembering window size and position seems to be an issue again in version 4.0.33.

Can you describe your monitor setup? Multiple monitors? Resolution on each? Where does Vysor place the windows when it restores vs where it was last?

**Comment by iamscottweber** [comment] 2021-04-16 19:56
Looks like this issue is resolved with version 4.0.35 already. Thanks!

**Comment by koush** [comment] 2021-04-16 21:20
> Looks like this issue is resolved with version 4.0.35 already. Thanks!

Yes, because I had to undo the fix. Can you describe your setup as I asked earlier?

**Comment by iamscottweber** [comment] 2021-04-19 14:45
> Can you describe your monitor setup? Multiple monitors? Resolution on each? 

I have two monitors, both are 23.5-inch (1920 x 1080).  

Where does Vysor place the windows when it restores vs where it was last?

Vysor opens on the left monitor, but I have all of the android window's set in order on the right monitor.

**Closed** 2021-07-11 16:20 UTC
Labels: fix pending
