### ISSUE TITLE
Vysor won't launch: Blank/Purple screen

### ISSUE THREAD

**Issue by murphyoself** [koush/vysor.io#853] opened 2021-07-15 17:34 UTC
(Original report Edited by @koush)

This is being caused by a bad route to Vysor's servers or ISP blocking `https://vysorelectron.clockworkmod.com`.

You can verify the issue by visiting https://vysorelectron.clockworkmod.com in your browser or running:

```sh
curl -v -v https://vysorelectron.clockworkmod.com
```

Currently there is a workaround by switching to the Beta channel which uses a different server:

Mac:

```sh
touch ~/Library/Application\ Support/vysor/beta-release-channel
```

Windows Command Prompt:

```sh
echo 'beta' > %APPDATA%\vysor\beta-release-channel
```

Linux:

```sh
touch ~/.config/vysor/beta-release-channel
```

History:

**7/13/2021**: Dr. Web marked this domain as not recommended which caused VirusTotal to mark it as malicious.
**7/15/2021**: Bad route to Fastly from Comcast users in the Bay Area.

<img width="855" alt="125995517-b471c4eb-6c6f-4cfc-a0e3-5d7bf3c74ac0" src="https://user-images.githubusercontent.com/73924/126010345-240320b1-743c-4786-991c-68ded656a103.png">

Original report follows:
---

Please help. I am a paid subscriber, and Vysor has been great for many months. However, yesterday I started up Vysor and it prompted me to update. After the update, all I see is a blue screen. Nothing seems to clear it the issue. See screenshot for details. 
<img width="1421" alt="Screen Shot 2021-07-15 at 10 34 05 AM" src="https://user-images.githubusercontent.com/87494152/125832031-1fad0969-adb7-4777-a91d-7325ba717a6b.png">

**Comment by koush** [comment] 2021-07-15 18:07
Can you please try restarting your Mac?

**Comment by koush** [comment] 2021-07-15 18:10
Also, are you behind a firewall or anything like that?

**Comment by murphyoself** [comment] 2021-07-15 18:37
> Can you please try restarting your Mac?

Already tried restart. Also tried to re-install. Is there a way to roll back my version?

**Comment by murphyoself** [comment] 2021-07-15 18:37
> Also, are you behind a firewall or anything like that?

No firewall.

**Comment by johnhshapiro** [comment] 2021-07-15 18:39
> > Can you please try restarting your Mac?
> 
> Already tried restart. Also tried to re-install. Is there a way to roll back my version?

I am experiencing the same issue, and I have tried the same steps. And I am also interested in the answer to this question. I reinstalled an older version I had saved on my laptop, but as soon as I relaunched Vysor it autoupdated and I faced the same issue.

**Comment by koush** [comment] 2021-07-15 19:05
Can you tell me the specs on your Macs?

**Comment by koush** [comment] 2021-07-15 19:05
I am creating a new build now that may provide more insight.

**Comment by murphyoself** [comment] 2021-07-15 19:09
> Can you tell me the mode/year on your Macs?

macOS Big Sur Version 11.4
MacBook Pro (13-inch, 2017)
2.3GHz Dual-Core Intel Core i5

**Comment by murphyoself** [comment] 2021-07-15 19:11
FYI - I did find an older version of Vysor in my downloads folder. So I am now up and running with 3.0.87. I will decline if a update message pops up. Hopefully it won't force me to update :-0

**Comment by johnhshapiro** [comment] 2021-07-15 19:12
> Can you tell me the mode/year on your Macs?

macOS Catalina Version 10.15.7
MacBook Pro (15-inch, 2019)

**Comment by koush** [comment] 2021-07-15 19:29
It will force an autoupdate unfortunately, but let's get this figured out.
Can you give this release a shot?

https://github.com/koush/vysor.io/releases/tag/v4.1.54

Also, you can join notes discord here and contact me if you have time to work through this in a screenshare session.

https://discord.gg/xR8DpZe7

**Comment by koush** [comment] 2021-07-15 19:45
Also please try loading this page in your browser:
https://vysorelectron.clockworkmod.com

It should just show a blank white page, but I want to confirm it's not blocked by your ISP (this was an issue in Israel earlier this week).

**Comment by koush** [comment] 2021-07-15 19:46
You are out of room on your phone
> android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space

**Comment by murphyoself** [comment] 2021-07-15 19:50
> Also please try loading this page in your browser:
> https://vysorelectron.clockworkmod.com
> 
> It should just show a blank white page, but I want to confirm it's not blocked by your ISP (this was an issue in Israel earlier this week).

I cannot access that page. It shows an error message. Failed to open page. 
<img width="530" alt="Screen Shot 2021-07-15 at 12 50 02 PM" src="https://user-images.githubusercontent.com/87494152/125848789-0e8793ec-b9fc-4da0-81f8-dce8df8b0745.png">

**Comment by koush** [comment] 2021-07-15 19:52
What country are you in?

**Comment by koush** [comment] 2021-07-15 19:52
Also try https://electron.vysor.io

**Comment by murphyoself** [comment] 2021-07-15 19:53
> What country are you in?

US, California on Xfinity/Comcast.

**Comment by murphyoself** [comment] 2021-07-15 19:53
> Also try https://electron.vysor.io

That one worked. Blank page, all white.

**Comment by koush** [comment] 2021-07-15 19:53
Strange, I'm on Comcast in Seattle

**Comment by koush** [comment] 2021-07-15 19:54
In a command prompt, try the following:

```sh
curl -v -v https://vysorelectron.clockworkmod.com/
```

And provide me the output.

**Comment by murphyoself** [comment] 2021-07-15 19:55
> In a command prompt, try the following:
> 
> ```shell
> curl -v -v https://vysorelectron.clockworkmod.com/
> ```
> 
> And provide me the output.
$ curl -v -v https://vysorelectron.clockworkmod.com/
*   Trying 185.199.111.153...
* TCP_NODELAY set
* Connected to vysorelectron.clockworkmod.com (185.199.111.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

**Comment by koush** [comment] 2021-07-15 20:01
Accidentally closed this issue with a comment meant for another bug, disregard.

**Comment by murphyoself** [comment] 2021-07-15 20:03
> It will force an autoupdate unfortunately, but let's get this figured out.
> Can you give this release a shot?
> 
> https://github.com/koush/vysor.io/releases/tag/v4.1.54
> 
> Also, you can join the discord here and contact me if you have time to work through this in a screenshare session.
> 
> https://discord.gg/xR8DpZe7

I tried this release 4.1.54 and the same issue with blue screen.

**Comment by koush** [comment] 2021-07-15 20:04
Please do the same with the other site so I can confirm:

```sh
curl -v -v https://electron.vysor.io/
```

**Comment by murphyoself** [comment] 2021-07-15 20:07
> Please do the same with the other site so I can confirm:
> 
> ```shell
> curl -v -v https://electron.vysor.io/
> ```

$ curl -v -v https://electron.vysor.io/
*   Trying 185.199.110.153...
* TCP_NODELAY set
* Connected to electron.vysor.io (185.199.110.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=electron.vysor.io
*  start date: Jul  2 23:24:46 2021 GMT
*  expire date: Sep 30 23:24:45 2021 GMT
*  subjectAltName: host "electron.vysor.io" matched cert's "electron.vysor.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f96a300d600)
> GET / HTTP/2
> Host: electron.vysor.io
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: GitHub.com
< content-type: text/html; charset=utf-8
< last-modified: Thu, 15 Jul 2021 16:35:36 GMT
< access-control-allow-origin: *
< etag: "60f063d8-d7b"
< expires: Thu, 15 Jul 2021 20:16:02 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: C72C:4687:2A5D1A:32AD8C:60F0952A
< accept-ranges: bytes
< date: Thu, 15 Jul 2021 20:06:02 GMT
< via: 1.1 varnish
< age: 0
< x-served-by: cache-pao17443-PAO
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1626379563.872773,VS0,VE93
< vary: Accept-Encoding
< x-fastly-request-id: 17ceb6b4227ba7b4efe2b6b0a3c59023f8f592c0
< content-length: 3451
< 
* Connection #0 to host electron.vysor.io left intact
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="origin-trial" content="Ans+Dieju+HiaUEl61Fgw+sax+cAz/KQ6kv1i6ZF67jJ+Sso4Ad93/462mJKkX727AAvYB1aobkiNfTefYtV/wAAAABeeyJvcmlnaW4iOiJodHRwczovL3Z5c29yLmlvOjQ0MyIsImZlYXR1cmUiOiJXZWJDb2RlY3MiLCJleHBpcnkiOjE2MjYyMjA3OTksImlzU3ViZG9tYWluIjp0cnVlfQ=="><title>Vysor</title><link href="/css/app.9b2b481c.css" rel="preload" as="style" integrity="sha256-8NHLLqGSleagW0bdIquC2vrSep4Ao0rOXd6o7ywZfFc= sha384-GDb6X/9VaqAWzyN0EuXVkndu1tYAYtKdD6OKls1yyjJcQvFgyaWivYpRIEaOJArD" crossorigin="anonymous"><link href="/css/chunk-vendors.a7178b82.css" rel="preload" as="style" integrity="sha256-KmGaXeCfHaepOTdPxCpBlET8Gb2DiNeytpuF6KBf0DQ= sha384-0joCQtye4AtMD6eHDCBMdJSzghJEzmP7MBFIrKWW4BJ7hYG08ECgIAmTouH+PgPw" crossorigin="anonymous"><link href="/js/app.fbe19a14.js" rel="preload" as="script" integrity="sha256-5Pb2gO7fn6keAjte+Ynbp3G/FKNsa4O4SRbWeDanUvw= sha384-6qG8ZysGqdHU9ERfA7LL8qwbYWn4PssLalz3NoyH1lkn//o9AGZQkdo/LeIYsV8q" crossorigin="anonymous"><link href="/js/chunk-vendors.fe551118.js" rel="preload" as="script" integrity="sha256-jIaaYtQ69TFAZx5YmjWnZTiKzRkwJ0ApScc1zf6Vvo0= sha384-vlcd9rVAuHKewFxuBgFWR7X/NYJ1pZAzw2tneArdP4PvVX8FFj38xoYCcYsNT+xS" crossorigin="anonymous"><link href="/css/chunk-vendors.a7178b82.css" rel="stylesheet" integrity="sha256-KmGaXeCfHaepOTdPxCpBlET8Gb2DiNeytpuF6KBf0DQ= sha384-0joCQtye4AtMD6eHDCBMdJSzghJEzmP7MBFIrKWW4BJ7hYG08ECgIAmTouH+PgPw" crossorigin="anonymous"><link href="/css/app.9b2b481c.css" rel="stylesheet" integrity="sha256-8NHLLqGSleagW0bdIquC2vrSep4Ao0rOXd6o7ywZfFc= sha384-GDb6X/9VaqAWzyN0EuXVkndu1tYAYtKdD6OKls1yyjJcQvFgyaWivYpRIEaOJArD" crossorigin="anonymous"><link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png" integrity="null" crossorigin="anonymous"><link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png" integrity="null" crossorigin="anonymous"><link rel="manifest" href="/manifest.json" integrity="null" crossorigin="anonymous"><meta name="theme-color" content="#3949AB"><meta name="apple-mobile-web-app-capable" content="no"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="Vysor"><link rel="apple-touch-icon" href="/img/icons/apple-touch-icon-152x152.png" integrity="null" crossorigin="anonymous"><link rel="mask-icon" href="/img/icons/safari-pinned-tab.svg" color="#3949AB" integrity="null" crossorigin="anonymous"><meta name="msapplication-TileImage" content="/img/icons/msapplication-icon-144x144.png"><meta name="msapplication-TileColor" content="#000000"></head><body oncontextmenu="return false;" style="user-select: none;"><noscript><strong>We're sorry but vysor doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.fe551118.js" integrity="sha256-jIaaYtQ69TFAZx5YmjWnZTiKzRkwJ0ApScc1zf6Vvo0= sha384-vlcd9rVAuHKewFxuBgFWR7X/NYJ1pZAzw2tneArdP4PvVX8FFj38xoYCcYsNT+xS" crossorigin="anonymous"></script><script src="/js/app.fbe19a14.js" integrity="sha256-5Pb2gO7fn6keAjte+Ynbp3G/FKNsa4O4SRbWeDanUvw= sha384-6qG8ZysGqdHU9ERfA7LL8qwbYWn4PssLalz3NoyH1lkn//o9AGZQkdo/LeIYsV8q" crossorigin="anonymous"></script></body></html>* Closing connection 0

**Comment by koush** [comment] 2021-07-15 20:21
Ok, quit vysor and run this:

```sh
touch ~/Library/Application\ Support/vysor/beta-release-channel
```

Then launch it again.
This will force you onto the beta channel which presumably should load. I'll need to figure out why this server hosted by Fastly/Github is failing. Typically it is resilient to server failures, since it caches the app on first launch (like when half the internet went down a few months ago), but it is failing after a first launch update...

**Comment by murphyoself** [comment] 2021-07-15 20:24
> Ok, quit vysor and run this:
> 
> ```shell
> touch ~/Library/Application\ Support/vysor/beta-release-channel
> ```
> 
> Then launch it again.
> This will force you onto the beta channel which presumably should load. I'll need to figure out why this server hosted by Fastly/Github is failing. Typically it is resilient to server failures, since it caches the app on first launch (like when half the internet went down a few months ago), but it is failing during the first launch.

Will give it a try, but before I do, which version of Vysor should I be running. The official release from the website? Or the 4.1.54 version you asked me to try earlier today?

**Comment by koush** [comment] 2021-07-15 20:31
The official release or the prerelease I linked earlier, but that workaround should work on any version.

**Comment by murphyoself** [comment] 2021-07-15 20:39
> The official release or the prerelease I linked earlier, but that workaround should work on any version.

OK got it. I tried the command you provided with the official release and I can confirm that both Android and iOS are working for me.

touch ~/Library/Application\ Support/vysor/beta-release-channel

**Comment by koush** [comment] 2021-07-16 02:13
Can you try checking https://vysorelectron.clockworkmod.com/ again?
I'm wondering if this was an intermittent issue.

**Comment by brettjcooper** [comment] 2021-07-16 13:51
I had the same issue for the last week and the commend "touch ~/Library/Application\ Support/vysor/beta-release-channel" worked to resolve the issue for me as well.

**Comment by murphyoself** [comment] 2021-07-16 15:16
> Can you try checking https://vysorelectron.clockworkmod.com/ again?
> I'm wondering if this was an intermittent issue.

Tried again with the same results. Failed to open page.

**Comment by koush** [comment] 2021-07-16 16:52
> I had the same issue for the last week and the commend "touch ~/Library/Application\ Support/vysor/beta-release-channel" worked to resolve the issue for me as well.

@brettjcooper 
Can you run the follow and give me the results:

```sh
curl -v -v https://vysorelectron.clockworkmod.com/
```

**Comment by brettjcooper** [comment] 2021-07-16 18:31
I get the following errors when i run wget/curl against that endpoint: 

| => wget https://vysorelectron.clockworkmod.com/
--2021-07-16 12:29:55--  https://vysorelectron.clockworkmod.com/
Resolving vysorelectron.clockworkmod.com (vysorelectron.clockworkmod.com)... 185.199.108.153, 185.199.110.153, 185.199.109.153, ...
Connecting to vysorelectron.clockworkmod.com (vysorelectron.clockworkmod.com)|185.199.108.153|:443... connected.
OpenSSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Unable to establish SSL connection.
________________________________________________________________________________
| => curl -v -v https://vysorelectron.clockworkmod.com/
*   Trying 185.199.108.153...
* TCP_NODELAY set
* Connected to vysorelectron.clockworkmod.com (185.199.108.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

**Comment by koush** [comment] 2021-07-16 18:46
@brettjcooper Can you check if you have xfinity advanced security enabled? https://www.xfinity.com/support/articles/using-xfinity-xfi-advanced-security

**Comment by koush** [comment] 2021-07-16 18:46
Also, please provide me a curl through the VPN, I wonder if it's resolving against a different IP.

**Comment by brettjcooper** [comment] 2021-07-16 19:00
I don't check on advanced security since I don't own the xfinity account.   

Here is the CURL request through VPN: 

curl -v -v https://vysorelectron.clockworkmod.com/
*   Trying 185.199.111.153...
* TCP_NODELAY set
* Connected to vysorelectron.clockworkmod.com (185.199.111.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=vysorelectron.clockworkmod.com
*  start date: Jul 10 05:46:18 2021 GMT
*  expire date: Oct  8 05:46:17 2021 GMT
*  subjectAltName: host "vysorelectron.clockworkmod.com" matched cert's "vysorelectron.clockworkmod.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbcdc00d600)
> GET / HTTP/2
> Host: vysorelectron.clockworkmod.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: GitHub.com
< content-type: text/html; charset=utf-8
< last-modified: Thu, 15 Jul 2021 16:37:25 GMT
< access-control-allow-origin: *
< etag: "60f06445-d7b"
< expires: Fri, 16 Jul 2021 19:08:39 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: FFB6:36FF:639271:8A6963:60F1D6DF
< accept-ranges: bytes
< date: Fri, 16 Jul 2021 18:58:39 GMT
< via: 1.1 varnish
< age: 0
< x-served-by: cache-den8263-DEN
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1626461920.550306,VS0,VE57
< vary: Accept-Encoding
< x-fastly-request-id: 8be69c467c2d1de17e03faaf069c91072c3e1643
< content-length: 3451
< 
* Connection #0 to host vysorelectron.clockworkmod.com left intact
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="origin-trial" content="Ans+Dieju+HiaUEl61Fgw+sax+cAz/KQ6kv1i6ZF67jJ+Sso4Ad93/462mJKkX727AAvYB1aobkiNfTefYtV/wAAAABeeyJvcmlnaW4iOiJodHRwczovL3Z5c29yLmlvOjQ0MyIsImZlYXR1cmUiOiJXZWJDb2RlY3MiLCJleHBpcnkiOjE2MjYyMjA3OTksImlzU3ViZG9tYWluIjp0cnVlfQ=="><title>Vysor</title><link href="/css/app.9b2b481c.css" rel="preload" as="style" integrity="sha256-8NHLLqGSleagW0bdIquC2vrSep4Ao0rOXd6o7ywZfFc= sha384-GDb6X/9VaqAWzyN0EuXVkndu1tYAYtKdD6OKls1yyjJcQvFgyaWivYpRIEaOJArD" crossorigin="anonymous"><link href="/css/chunk-vendors.a7178b82.css" rel="preload" as="style" integrity="sha256-KmGaXeCfHaepOTdPxCpBlET8Gb2DiNeytpuF6KBf0DQ= sha384-0joCQtye4AtMD6eHDCBMdJSzghJEzmP7MBFIrKWW4BJ7hYG08ECgIAmTouH+PgPw" crossorigin="anonymous"><link href="/js/app.fbe19a14.js" rel="preload" as="script" integrity="sha256-5Pb2gO7fn6keAjte+Ynbp3G/FKNsa4O4SRbWeDanUvw= sha384-6qG8ZysGqdHU9ERfA7LL8qwbYWn4PssLalz3NoyH1lkn//o9AGZQkdo/LeIYsV8q" crossorigin="anonymous"><link href="/js/chunk-vendors.fe551118.js" rel="preload" as="script" integrity="sha256-jIaaYtQ69TFAZx5YmjWnZTiKzRkwJ0ApScc1zf6Vvo0= sha384-vlcd9rVAuHKewFxuBgFWR7X/NYJ1pZAzw2tneArdP4PvVX8FFj38xoYCcYsNT+xS" crossorigin="anonymous"><link href="/css/chunk-vendors.a7178b82.css" rel="stylesheet" integrity="sha256-KmGaXeCfHaepOTdPxCpBlET8Gb2DiNeytpuF6KBf0DQ= sha384-0joCQtye4AtMD6eHDCBMdJSzghJEzmP7MBFIrKWW4BJ7hYG08ECgIAmTouH+PgPw" crossorigin="anonymous"><link href="/css/app.9b2b481c.css" rel="stylesheet" integrity="sha256-8NHLLqGSleagW0bdIquC2vrSep4Ao0rOXd6o7ywZfFc= sha384-GDb6X/9VaqAWzyN0EuXVkndu1tYAYtKdD6OKls1yyjJcQvFgyaWivYpRIEaOJArD" crossorigin="anonymous"><link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png" integrity="null" crossorigin="anonymous"><link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png" integrity="null" crossorigin="anonymous"><link rel="manifest" href="/manifest.json" integrity="null" crossorigin="anonymous"><meta name="theme-color" content="#3949AB"><meta name="apple-mobile-web-app-capable" content="no"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="Vysor"><link rel="apple-touch-icon" href="/img/icons/apple-touch-icon-152x152.png" integrity="null" crossorigin="anonymous"><link rel="mask-icon" href="/img/icons/safari-pinned-tab.svg" color="#3949AB" integrity="null" crossorigin="anonymous"><meta name="msapplication-TileImage" content="/img/icons/msapplication-icon-144x144.png"><meta name="msapplication-TileColor" content="#000000"></head><body oncontextmenu="return false;" style="user-select: none;"><noscript><strong>We're sorry but vysor doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.fe551118.js" integrity="sha256-jIaaYtQ69TFAZx5YmjWnZTiKzRkwJ0ApScc1zf6Vvo0= sha384-vlcd9rVAuHKewFxuBgFWR7X/NYJ1pZAzw2tneArdP4PvVX8FFj38xoYCcYsNT+xS" crossorigin="anonymous"></script><script src="/js/app.fbe19a14.js" integrity="sha256-5Pb2gO7fn6keAjte+Ynbp3G/FKNsa4O4SRbWeDanUvw= sha384-6qG8ZysGqdHU9ERfA7LL8qwbYWn4PssLalz3NoyH1lkn//o9AGZQkdo/LeIYsV8q" crossorigin="anonymous"></script></body></html>* Closing connection 0

**Comment by koush** [comment] 2021-07-16 20:35
Can you check again, I migrated the site from Fastly/Github to AWS.

**Comment by murphyoself** [comment] 2021-07-16 20:39
> Can you check again, I migrated the site from Fastly/Github to AWS.

I just tried https://vysorelectron.clockworkmod.com/ and it worked. Connected to a blank white page.

**Comment by koush** [comment] 2021-07-16 20:49
Great, I suspect the app should work as well now. Please confirm.

**Comment by brettjcooper** [comment] 2021-07-16 20:54
That worked.

**Comment by koush** [comment] 2021-07-16 21:00
Ok, I'm going to leave this issue open and follow up with Fastly/Github. AWS hosting is just a stopgap as I don't want to use them as my provider long term.

**Comment by smaeda-ks** [comment] 2021-07-17 04:34
@brettjcooper Are you still getting the same? Could you please try the following from the problematic network?

```
$ openssl s_client -showcerts -servername vysorelectron.clockworkmod.com -connect 185.199.108.153:443 2>&1 </dev/null

$ openssl s_client -showcerts -servername vysorelectron.clockworkmod.com -connect 185.199.109.153:443 2>&1 </dev/null

$ openssl s_client -showcerts -servername vysorelectron.clockworkmod.com -connect 185.199.110.153:443 2>&1 </dev/null

$ openssl s_client -showcerts -servername vysorelectron.clockworkmod.com -connect 185.199.111.153:443 2>&1 </dev/null
```

and tell me if you get any errors other than `Verify return code: 0 (ok)` successful message.

**Comment by brettjcooper** [comment] 2021-07-17 22:02
It looks like i got successful return codes,  same response for all four:     openssl s_client -showcerts -servername vysorelectron.clockworkmod.com -connect 185.199.111.153:443
CONNECTED(00000003)
4439432812:error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.140.1/libressl-2.8/ssl/ssl_pkt.c:386:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1626559283
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

**Comment by smaeda-ks** [comment] 2021-07-18 02:18
ok, then things semm to be recovered naturally.

**Closed** 2021-07-27 18:03 UTC
