### ISSUE TITLE
Slow after andriod 10 update

### ISSUE THREAD

**Issue by Therepup** [koush/vysor.io#879] opened 2021-07-27 18:58 UTC
https://gist.github.com/b8dc83462a6a70fa9b92b802a458231f
https://prnt.sc/1gpsisp
https://prnt.sc/1gpsq6x
zte 2050
android 10
gpu radeon rx 570 8gb
Processor AMD FX-8320E Eight-Core Processor                 3.20 GHz
Installed RAM	16.0 GB

**Comment by koush** [comment] 2021-07-27 19:24
thanks taking a look

**Comment by koush** [comment] 2021-07-27 19:24
Just to be certain, please try restarting your computer and phone as well.

**Comment by koush** [comment] 2021-07-27 19:25
After restarting, also try the following decoders:

WebCodec Hardware + Fallback
and
WebAssembly

**Comment by Therepup** [comment] 2021-07-28 15:00
Neither of those option worked is still mega slow

**Comment by koush** [comment] 2021-07-30 17:13
Can you verify this is happening on the 4.1.70 update I released yesterday? Another user confirmed it fixed. https://github.com/koush/vysor.io/issues/882

You may need to click "Defaults" in Vysor's device settings.

**Comment by Therepup** [comment] 2021-07-30 17:17
How do I update the vysor? Mines is still in 4.1.62

**Comment by Therepup** [comment] 2021-07-30 17:20
Never mind the runtime is  .62 the version is .70 it still happening.

**Comment by koush** [comment] 2021-07-30 17:35
You restored to defaults and retried the different decoders?

**Comment by Therepup** [comment] 2021-07-30 17:44
I did restore default and tried all the decoders yes

**Comment by koush** [comment] 2021-08-05 04:02
Can you make a video of what the performance looks like? Screen recording?

**Comment by Therepup** [comment] 2021-08-06 20:11
https://www.youtube.com/watch?v=DW2NICOAQnI

**Comment by koush** [comment] 2021-08-24 17:58
I think this might be fixed in v4.1.92 (Runtime v4.1.77)

**Closed by koush** 2021-08-24 17:58 UTC
